### ISSUE TITLE
ajaxuploader requirement

### ISSUE THREAD

**Issue by lyssdod** [mbraak/django-file-form#110]
Hi,

Do you plan to support https://github.com/skoczen/django-ajax-uploader as a requirement? You have slightly outdated version in the repo which lacks many backends present in the current version of django-ajax-uploader.

**Comment by mbraak** [comment]
Django-file-form uses a patched version of the `django-ajax-uploader` package. I'm afraid the patched version is not compatible with the original `django-ajax-uploader`.

I hope this is not a problem. Are you planning to use a different backend?

**Comment by lyssdod** [comment]
What kind of patches do you use? Is it possible to resolve it via creating some parent meta class? I thought maybe create pure static fineuploader package, based on upstream js version and use it as a requirement, thus your project will be fully modular; long story short, trying to use easy-thumbnails for ajax-powered multiple image upload

**Comment by mbraak** [comment]
I'm afraid you cannot use an upload backend from django-ajax-uploader, because django-file-form uses its own backend (FileFormUploadBackend).

Perhaps it is possible to override the backend. Let me see if I have an example.

**Comment by mbraak** [comment]
I think the best way to create thumbnails is to handle that in the `view.form_valid`.
