### ISSUE TITLE
UploadWidget without the link to current file and clear options

### ISSUE THREAD

**Issue by erfaan** [mbraak/django-file-form#136]
Can we add another widget which works just like Django's `FileInput` instead of `ClearableFileInput`?

**Comment by mbraak** [comment]
Perhaps it would be a good idea to add the `clearable` option. It would look something like this:

```python
class ExampleForm(FileFormMixin, forms.Form):
    input_file = UploadedFileField(clearable=False)
```

Would this work for you?

**Comment by erfaan** [comment]
That looks good but a more "djangoish" way would be able to specify the `widget` 

```python
class ExampleForm(FileFormMixin, forms.Form):
    input_file1 = UploadedFileField(widget=UploadWidgetClearable)
    input_file2 = UploadedFileField(widget=UploadWidget)
```

**Comment by mbraak** [comment]
Yes, I think that is a good idea. And then it would be possible to make your own widget.

**Comment by mbraak** [comment]
In which situation do you use the non-clearable widget? I tested this with the example project, and I saw no difference.

**Comment by mbraak** [comment]
I added a UploadWidgetMixin class to widgets.py that makes it possible to create your own widget:

```python
from django_file_form.widgets import UploadWidgetMixin
from django.forms import FileInput

class MyUploadWidget(UploadWidgetMixin, FileInput):
    pass
```

You can then use this in a form:

```python
class ExampleForm(BaseForm):
    input_file = UploadedFileField(widget=MyUploadWidget)
```

The new code is in the master branch. Please let me know if this works.

**Comment by mbraak** [comment]
Closing the issue
