### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by nichcz** [mbraak/django-file-form#145]
```
  File "/virtual/local/lib/python2.7/site-packages/django_file_form/models.py", line 58, in __str__
    return str(self.original_filename or '')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 17: ordinal not in range(128)
```

```
    def __str__(self):
        return str(self.original_filename or '')
```

Is neccessary to wrap return value with `str`? https://docs.djangoproject.com/en/1.10/ref/models/instances/#other-model-instance-methods

I would maybe recommend `six.text_type` instead https://pythonhosted.org/six/#six.text_type

**Comment by mbraak** [comment]
I'll look into it

**Comment by mbraak** [comment]
This is now fixed in the `master` branch
