### ISSUE TITLE
Migration not delivered via pip.

### ISSUE THREAD

**Issue by Loisel** [mbraak/django-file-form#148]
There seem to be a migration missing in the python package:

    Migrations for 'django_file_form':
      /usr/local/lib/python2.7/site-packages/django_file_form/migrations/0002_auto_20170316_0908.py:
        - Alter field uploaded_file on uploadedfile

This file is present in the repo.

**Comment by mbraak** [comment]
It seems that did migration was not necessary. I removed it now from the repository.

**Comment by Loisel** [comment]
Afaik removing the migration does not fix the issue since it is auto-generated upon `manage.py makemigrations` and is related to a change in the model. If it is not a necessary change to the model please consider undoing the change, thus making the migration obsolete.

Second option is to add the migration to the PyPI package (this is the easiest solution).

**Comment by mbraak** [comment]
I updated the package on pypi. This version includes the migration.

**Comment by Loisel** [comment]
Thanks a lot. I appreciate the immediate response!
