### ISSUE TITLE
MultiUploadedFileField seems to loose filename extension upon upload.

### ISSUE THREAD

**Issue by Loisel** [mbraak/django-file-form#151]
For files uploaded via `MultiUploadedFileField` the filename extension is not preserved:

    In [3]: m.img.url
    Out[3]: '/media/materials/2017-03-24-11-57-06_IMG_1780'

which used to be a `.JPG`. Same procedure for `UploadedFileField` works as expected:

    In [11]: w.img.url
    Out[11]: '/media/materials/tub1.jpg'

**Comment by mbraak** [comment]
That' s strange. I tried to reproduce this in the testproject, but I don't get this error. I used Django 1.10.6 and Chrome on Osx.

**Comment by Loisel** [comment]
Ah I'm sorry this was my mistake. I'll promise to test in the testproject before I file an issue next time. Thanks for your effort.
