### ISSUE TITLE
Duplicate queries

### ISSUE THREAD

**Issue by Benoss** [mbraak/django-file-form#156]
Having a form with 2 upload fields Django is doing 4 queries to the backend.
2 would be the maximum (one query per field)
1 query total is doable by getting all django_file_form_uploadedfile for a given form_id and then injecting each field_name

 	+ 	
SELECT ••• FROM "django_file_form_uploadedfile" WHERE ("django_file_form_uploadedfile"."field_name" = '''photo_id''' AND "django_file_form_uploadedfile"."form_id" = '''a1ecf120-38d7-4272-8e37-f95ca8ffea0d''') LIMIT 1

  	+ 	
SELECT ••• FROM "django_file_form_uploadedfile" WHERE ("django_file_form_uploadedfile"."field_name" = '''photo_id''' AND "django_file_form_uploadedfile"."form_id" = '''a1ecf120-38d7-4272-8e37-f95ca8ffea0d''') ORDER BY "django_file_form_uploadedfile"."created" DESC LIMIT 1

  	+ 	
SELECT ••• FROM "django_file_form_uploadedfile" WHERE ("django_file_form_uploadedfile"."field_name" = '''photo_id_2''' AND "django_file_form_uploadedfile"."form_id" = '''a1ecf120-38d7-4272-8e37-f95ca8ffea0d''') LIMIT 1

  	+ 	
SELECT ••• FROM "django_file_form_uploadedfile" WHERE ("django_file_form_uploadedfile"."field_name" = '''photo_id_2''' AND "django_file_form_uploadedfile"."form_id" = '''a1ecf120-38d7-4272-8e37-f95ca8ffea0d''') ORDER BY "django_file_form_uploadedfile"."created" DESC LIMIT 1

**Comment by mbraak** [comment]
Thanks for the suggestion. I have never looked into the query performance for this project, but this is quite interesting.

I changed the code so it will do 1 query per field.

I have looked into the possibility to do 1 single query, but I don't want to do that at this moment. The query itself is quite easy, but it will make the python code that handles the query more difficult.
