### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Benoss** [mbraak/django-file-form#165]
Hello,

Would it be possible to have a new package release?
We had a collision of hash because of this issue.
https://github.com/mbraak/django-file-form/pull/154

Thank you

**Comment by mbraak** [comment]
Hello Benoit,

I will release a new version in a few days.

Greetings,
Marco

**Comment by mbraak** [comment]
Version 0.2.4 is released

**Comment by Benoss** [comment]
Thanks ;)
