### ISSUE TITLE
test_submit_multiple_without_ajax doesn't actually upload multiple files

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#198]
Hi there,

I'm trying to test my own form that uses MultipleUploadedFileField.
I can't figure out how to test for multiple files so I wanted to check out your testproject.
It seems though that your test doesn't upload multiple files without ajax...
I normally test by opening a file on disk and adding that file to the filefield in the dictionary that I post to the page containing the form. However you can't open multiple files and add them all at the same time. Do you have tips to approach this and what does the test for uploading multiple files actually look like?

Thanks!

Regards, Ellen

**Comment by mbraak** [comment]
Hello,

Sorry for my late reaction. It seems that multiples files upload without ajax is broken.

I have added a pr to fix this: https://github.com/mbraak/django-file-form/pull/201. I will release a new version when the pr is finished.

Greetings,
Marco

**Comment by Lionqueen94** [comment]
Thanks for your response! I use Django Unittest Testcases myself, and I've been wrecking my brain to think of a way to test my code with multiple files, but I just can't figure it out. I think I need to do my testing with Selenium tests and therefor using the Ajaxuploader. I really hope there is a possibility to test this field in the backend though 😇
