### ISSUE TITLE
UploadedFileField within Wizards

### ISSUE THREAD

**Issue by iw108** [mbraak/django-file-form#206]
Hi, 

I'm currently trying to split a form across multiple views using the django-formtools Wizard application. In a number of these subforms I need to upload files and I was hoping to implement django-file-forms' UploadedFileField/MultipleUploadedFileField to do this. In regular, non-wizard, forms these fields always work, however, within wizard related forms I consistently get the following console error: 'upload_url field is empty; aborting initialization'. It isn't clear to me what is causing this error - perhaps the FileFormMixin is not initializing? I was wondering if you had any ideas as to what is causing this/ how it can be resolved? 

Thanks in advance for your help and for all your efforts!
Isaac

**Comment by mbraak** [comment]
Hello,

The javascript code for `django-file-form` looks for an input with the name `upload_url`. If it cannot find the input, then it outputs this error message.

The input field should look something like this:

```
<input name="upload_url" />
```

My guess is that the input in your wizard form has a different name. Please let me know if that is the case, perhaps I can find a solution.

Greetings

**Comment by mbraak** [comment]
I think that the `django-form-tools` wizard uses a form prefix. That doesn't work because `django-file-form` 0.4.1 did not support prefixes.

I added support for prefixes in the new version (0.4.2).

You should change the call to `initUploadFields` to use the correct prefix. I don't know what the prefix is in your case.

For example:

```js
  // for example, with prefix 'abc'
  initUploadFields($('#example-form'), { prefix: 'abc' });
```

Greetings

**Comment by iw108** [comment]
Hi, 

You were correct about the prefixes - everything works as expected with the latest version. Thank you very much for resolving this and so quickly!

Isaac
