### ISSUE TITLE
obsolete pathlib dependency break other modules

### ISSUE THREAD

**Issue by maisim** [mbraak/django-file-form#208]
Hello,
django-file-form depends on obsolete pathlib module [1]  that override the native pathlib module (new in python3.4 [2]) and break other modules that use missing functionalities in this old external pathlib module

That seems dependency can be remove for python3 install without problem.
Big thanks for your work on django-file-form
Simon

[1] https://bitbucket.org/pitrou/pathlib/
[2] https://docs.python.org/3.5/library/pathlib.html

**Comment by mbraak** [comment]
Fixed by pr. Closing the issue.
