### ISSUE TITLE
Self execute javascript on window ready 

### ISSUE THREAD

**Issue by ph00lt0** [mbraak/django-file-form#211]
It would be great if no inline JavaScript would be required. This for better practice and security. 

**My suggestion:** 
Use self execute on` $(document).ready()` and instead of requiring an argument let users add a data-attribute to the form. 

So instead of the inline script `initUploadFields($('#example-form'));` use something like             `<form method="POST" novalidate {{{data-upload-fields}}}>` Then loop over the forms that have this attribute.

**Comment by mbraak** [comment]
Thanks for the suggestion. I will look into it.

**Comment by yedpodtrzitko** [comment]
@ph00lt0 what's your idea about passing custom options with such implementation?

**Comment by mbraak** [comment]
This is a new feature in version 3.1.5. See http://mbraak.github.io/django-file-form/auto_initialize/

**Comment by ph00lt0** [comment]
@mbraak thank you for the addition, will look into :)
