### ISSUE TITLE
Fine Uploader  is no longer maintained (deprecated)

### ISSUE THREAD

**Issue by dureba** [mbraak/django-file-form#214]
Sad news but:
Fine Uploader is no longer maintained and the project has been effectively shut down.
For more info, see https://github.com/FineUploader/fine-uploader/issues/2073

Should we find another lib?

Btw, thanks a lot for the django-file-form lib ;)

**Comment by mbraak** [comment]
Yes, using another library is perhaps a good idea.

I see there is a fork of fine-uploader with recent commits: https://www.npmjs.com/package/@blue-billywig/fine-uploader. So maybe that's also an option.

**Comment by mbraak** [comment]
I'm looking at https://tus.io/ to replace fineupload

**Comment by mbraak** [comment]
This issue is fixed in version 2.0: it uses `tus.io` instead of fineupload
