### ISSUE TITLE
using with formset

### ISSUE THREAD

**Issue by jucajuca** [mbraak/django-file-form#237]
Hello,
we want to have multiple fields to upload images. 
We have been trying to wrap the UploadedFileField in a Django FormSet without sucess. Do you have any idea how can we achieve this?

**Forms.py**
```
class MediaForm_test(FileFormMixin, forms.Form):
    image = UploadedFileField( required=False  )
    name_for = CharField( required=False )
    copyright = CharField( required=False )

    def __init__(self, *args, **kwargs):
        super(MediaForm_test, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

MediaFormSet = formset_factory(MediaForm_test, extra=7)
```

**views.py**
```
class NewSubmitView(LoginRequiredMixin, FormView):
    use_ajax = True
    template_name = 'jurysys/add.html'

    def get(self, request,*args, **kwargs):

        context = request.GET.dict()
        context['pics'] =           MediaFormSet
        context['pics_helper'] =    MediaFormsetHelper()

        context['use_ajax'] = True

        return render(request, self.template_name, context)

    def post(self, request):

        pics_f      = MediaFormSet(request.POST, request.FILES)

        i=0
        if pics_f.is_valid():
            for pic in pics_f:
                pic_ =  media()
                if pic.is_valid():
                    pic_.project = project
                    image = pic.cleaned_data['image']
                    name = image.name
                    pic_.filename = name
                    pic_.save()
                    pic.delete_temporary_files()
                    i+=1
        else:
            print (pics_f.errors)
```

@l0tt

**Comment by mbraak** [comment]
I will have a look it.

**Comment by mbraak** [comment]
I'm afraid formsets are not supported at this moment. It looks like the python part may work, but the javascript needs some adjustments. 

My plan is to add support in the future; but that's going to be after the release of version 1.0.

**Comment by mbraak** [comment]
Formset support is now in master, not yet in a release.

Use  `initFormSet` (instead of `initUploadFields`) in your javascript code.

```js
initFormSet(
  document.getElementById("example-form"),
  "form"
);
```

Also see the testproject directory in the repository for an example.

**Comment by gzubicki** [comment]
I can't do this. 
I try with formsets input in one form, like:

` <form method="post" id="advert-form" enctype="multipart/form-data">	
	{% csrf_token %}
	<fieldset>

	<div class="center form">

		{% crispy form form.helper %}
		
		{% for formset in inlines %}
		    {{ formset|crispy }}
		  {% endfor %}
		<div class="form-actions mt-5">
		{% block listButtons %}
			<input type="submit" value="Zapisz" class="btn btn-succes cosmet_button">
		{% endblock %}
		</div>

	</div>    

	</fieldset>
	</form>
`
and :
`<script type="text/javascript" >
$(function() {
	initFormSet(
		    document.getElementById("advert-form"),
		    "",
		    { skipRequired: true },
		);
});
</script>    `

It doesn't  work, can you explain template structure, your JS is compress, i can't analyze it

**Comment by mbraak** [comment]
I added an uncompressed javascript version. It's in [this branch](https://github.com/mbraak/django-file-form/tree/include-uncompressed-js). The original source code is in `frontend/file_form.js`.

Does your formset have a prefix? If so, you must set it as the second parameter of `initFormSet` (instead of an empty string). The default prefix in Django is `form`.

Also see https://docs.djangoproject.com/en/3.0/topics/forms/formsets/#customizing-a-formset-s-prefix

**Comment by gzubicki** [comment]
Thanks for very fast response. 
I had problem because you have hardcoded prefix here:


  for (var i = 0; i < formCount; i += 1) {
    var subFormPrefix = getInputNameWithPrefix("".concat(i));
    initUploadFields(form, {
      prefix: "form-".concat(subFormPrefix)
    });

**Comment by gzubicki** [comment]
Next problems:
1) standard FILE_FORM_UPLOAD_DIR was broken ='/tem_uploads' i fix it in my own settings.py
FILE_FORM_UPLOAD_DIR = os.path.join(MEDIA_ROOT, 'temp_uploads') 

2) After submit form with formstes i have "The file cannot be reopened." - I will report when i fix it

**Comment by mbraak** [comment]
Thanks for finding these issues. I have made pr's to fix them. They will be merged shortly.

* Fix default for FILE_FORM_UPLOAD_DIR
* Correctly use formset prefix

**Comment by mbraak** [comment]
Pr's mentioned above are in new release `2.0.3`.
