### ISSUE TITLE
Rendering fields manually don't work

### ISSUE THREAD

**Issue by pitonoved** [mbraak/django-file-form#238]
Hello, thank you for this lib) But I have a problem - I can't use rendering fields manually. For  exemple: if put `{{ form.input_file }}` in my template - it don`t work. Field rendering without styles and js.

In the same time, tag `{{ form.as_p }}` work normal.

If enter the first line of `{{ form.as_p }}`, and then `{{ form.input_file }}` - field `input_file` rendering normal too.

Sorry for my English)

**Comment by mbraak** [comment]
Hello, 

The reason that your form doesn't render, is because the hidden fields are not rendered. You can render them this way:

```
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
```

I will add this to the documentation.

Greetings

**Comment by pitonoved** [comment]
> 
> 
> Hello,
> 
> The reason that your form doesn't render, is because the hidden fields are not rendered. You can render them this way:
> 
> ```
> {% for hidden in form.hidden_fields %}
>     {{ hidden }}
> {% endfor %}
> ```
> 
> I will add this to the documentation.
> 
> Greetings

Thank! Problem resolved!)
