### ISSUE TITLE
Request: Please (make an option to) pre initialize div class="dff-files"

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#240]
Hi there,

Thanks a lot for the update of django-file-form to remove the deprecated fineuploader.
I would like to request an update to give the option (or just always) pre initialize the
`<div class="dff-files">`
I have a mutations observer that observes the list of uploads and executed a function every time a file is uploaded, however, my observer does not observe anything since the div is nonexistent before the first file is uploaded.

I hope this change can be made.

Thanks!

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I added a pr with a solution: #243 The pr will be merged soon

**Comment by Lionqueen94** [comment]
Awesome! Thanks a lot for the fast changes, looking forward to the merge request :)

**Comment by mbraak** [comment]
I released version 2.0.1 with a fix for this issue
