### ISSUE TITLE
Request: Please make the js file CSP compliant without using 'unsafe-eval'

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#241]
Hi there,

I noticed that eval is used in the javascript file and the CSP set on our website does not appreciate that. Would it be possible to change the uses of eval() (and possibly other functions) in the source code? I really appreciate the work and that this app is actively maintained.

Thanks!

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I added this pr with the fix: #242 It will be merged soon

**Comment by Lionqueen94** [comment]
Great! Thanks a lot for the fast changes, looking forward to the merge request and seeing if it all works :)

**Comment by mbraak** [comment]
I released version 2.0.1 with a fix for this issue
