### ISSUE TITLE
Fileform breaks in a form wizard

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#247]
Thanks for the previous fixes for my requests, they work great!

Now I found 2 more issues uploading and deleting files.
In the first issue I upload a file in a single upload field in my formtools SessionWizardView. Click next to go to the next page, go back and then try to delete the file. This causes a:
`file_form.js:8 Uncaught TypeError: Cannot read property 'url' of undefined`
![Screenshot from 2020-01-06 10-15-08](https://user-images.githubusercontent.com/2974080/71808480-2a27ab00-306e-11ea-936e-3e50fb711fc8.png)

The file still exists on disk, but somehow the object gets 'lost' in a form wizard?

Another (I think related) issue is if there are errors in the file on posting the first page of the form.
What happens then is if you select a new file, the previous file does not get removed, another Delete link shows up and the new file is forever uploading. However, there is no error in the console when this happens.
![Screenshot from 2020-01-06 10-29-16](https://user-images.githubusercontent.com/2974080/71809008-758e8900-306f-11ea-8005-98ace71342d9.png)
![Screenshot from 2020-01-06 10-29-32](https://user-images.githubusercontent.com/2974080/71809009-758e8900-306f-11ea-9bca-37f4c30baf5c.png)

Please let me know if I can provide more information to debug these issues, for now we will just keep using the 1.0.1 version in production so there is no rush.

Thanks!

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
Both issues are now hopefully fixed. I will release a new version soon.

**Comment by mbraak** [comment]
I added an example wizard to the test project. The only custom code for the wizard is the javascript: https://github.com/mbraak/django-file-form/blob/master/testproject/django_file_form_example/static/wizard_form.js

* Call `initUploadFields` only for wizard steps with an upload
* Set the correct prefix. The default for the wizard is the index of the step; `0` for the first step.

**Comment by mbraak** [comment]
Fixed in releases `2.0.2`
