### ISSUE TITLE
Missing template django_file_form/upload_template.html

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#264]
The documentation asks to

```
{% include 'django_file_form/upload_template.html' %}
```

but the pip version and the trunk only has `upload_widget.htm`. Should `upload_widget.html` be included instead?

**Comment by mbraak** [comment]
It's no longer necessary to include this template (since version 1.0). I'll update the documentation.

Thanks for finding this issue!

**Comment by BoPeng** [comment]
Thanks. This is good to know because I was wondering how to include it with my jinja2 template.

The field does not work out of box for me so I am reading the source code to debug it. Basically, I have

1. A model with a lot of other fields, and a `m2m` field to a dedicated table of uploaded files (that could be shared by multiple instances).
2. A `ModelForm` currently with the rest of the fields, and an extra `MultpleUploadedFileField` for the `m2m` field. I was hoping to add to the `m2m` field in the `Form.save` method.

The frontend seems to be working but the uploaded files are not displayed (no feedback list). I am trying to read the source code and figure out how this app works. As far as I can tell

1. There is a backend and URL system.
2. The frontend, the JS part works with the `file-form` backend to upload files to its own `uploaded` table. So there must be separate `POST` request sent by the widget.
3. With the `POST` request from the big form, users should process the uploaded file and remove the temporary files from the `file-form` backend.

I think I am stuck at step 2 where the reply from the `file-form` backend does not display in my big form. 

A further problem is that I will have to customize the reply from `file-form` backend because I would like to ask users to add "descriptions" to their upload files. So some dynamic fields will be created with each upload file, in addition to the `delete` button etc. Looks very challenging to me but hopefully doable.

**Comment by BoPeng** [comment]
The reason why upload did not work is 

https://github.com/mbraak/django-file-form/blob/c299dff67b9688e83c19a386194a8afeb976c772/frontend/file_form.js#L287

```
jquery-3.4.1.min.js:2
Uncaught TypeError: e.querySelector is not a function
    at p (file_form.js:287)
    at o (file_form.js:317)
    at h (file_form.js:329)
    at HTMLDocument.<anonymous> (workflow:552)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
```

so there could be a jquery version problem....

**Comment by BoPeng** [comment]
Update:

```
initUploadFields($('#example-form'), 
```
does not work. The error message is gone if I change it to

```
initUploadFields(document.getElementById("example-form")
```
so maybe `jquery` `$` should not be used here.

**Comment by BoPeng** [comment]
Next one :-), all file upload fails.

```
upload.js:445 POST http://0.0.0.0:8000/~upload/upload/ 500 (Internal Server Error)
value @ upload.js:445
(anonymous) @ upload.js:254
value @ storage.js:49
(anonymous) @ upload.js:244
t.default @ fingerprint.js:26
value @ upload.js:237
(anonymous) @ upload.js:137
t.getSource @ source.js:192
value @ upload.js:129
(anonymous) @ file_form.js:222
(anonymous) @ file_form.js:209
```

**Comment by mbraak** [comment]
Thanks! I'll update the documentation.
