### ISSUE TITLE
Why not FILE_FORM_UPLOAD_DIR be a directory under MEDIA_ROOT?

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#266]
Not a big deal but instead of 

https://github.com/mbraak/django-file-form/blob/7ddff88d5430c2da08a3557b11776b09e1ec3bd6/django_file_form/conf.py#L5

I am wondering if it is better to do

```python
 UPLOAD_DIR = os.path.join(settings.MEDIA_ROOT, 
    getattr(settings, 'FILE_FORM_UPLOAD_DIR', 'temp_uploads')) 
```
because having users to repeat `MEDIA_ROOT` in `FILE_FORM_UPLOAD_DIR` can be a source of error.

Note that this would also conforms to the convention of other django configurations such as `FileField(upload_to)` where `upload_to` should be or return a directory under `MEDIA_ROOT`.

**Comment by mbraak** [comment]
Sounds like a good idea if this is a convention. I'll see if there is a way to change this without breaking existing projects.

**Comment by BoPeng** [comment]
Generally speaking there is no backward compatible way to change it. I would choose another name (e.g. `FILE_FORM_STORAGE_DIR`) and keep the existing one working but undocumented.

**Comment by mbraak** [comment]
This is now fixed in master. `FILE_FORM_UPLOAD_DIR` can be relative and absolute (the code check if the setting is an absolute path).
