### ISSUE TITLE
Inserting existing files to the list of uploaded files.

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#269]
I am using `django-file-form` to upload `attachments` to my objects and it is working fine for uploading files. However, when I try to let users update the `attachments`, I will need to add the existing attachments (which are supposed to be removed from `UploadedFile` already) to the uploaded file list and introduce my own view for users to delete them, while allowing `django-file-form` to add new attachments.

What is the recommended way of doing this? I can imagine the following solutions:

1. Add existing attachments to the `UploadedFile` table and allow `django-file-form` to add/remove all attachments, and check which attachments are newly added, which are removed, which are replaced etc.
2. Insert existing attachments to the widget (somehow) and supply my own `remove` link to remove attachments from my model. It would be difficult to implement "replace" action in this method.
3. Use `UploadedFile` as permanent storage for attachments by linking the files to my model using a `m2m` relationship. This looks cleanest but I am not sure it can be done within the current framework of `django-file-form` because it is designed for temporary storage.

I would appreciate any comment as the best way to proceed. Thanks!

**Comment by BoPeng** [comment]
For anyone who encounters the same need, here is what I have done so far

```
    def get_initial(self):
        init = super(mymodel, self).get_initial()
        obj = self.get_object()
        # if there are existing attachment, let us fake something under the temp
        # upload directory to allow users to remove or update it (download is another story though)
        init['attachments'] = []
        for obj in obj.attachments.all():
            fake_id = uuid.uuid4().hex
            fake_path = os.path.join(settings.MEDIA_ROOT,
                                     settings.FILE_FORM_UPLOAD_DIR, fake_id)
            with open(fake_path, 'w') as fake_file:
                fake_file.write(obj.file_name)
            # insert the fake file into the database
            uploaded_file = UploadedFile.objects.create(
                file_id=fake_id,
                form_id=fake_id,  # this is not the correct form_id
                uploaded_file=fake_path,
                original_filename=obj.file_name,
                field_name='attachment')
            init['attachments'].append(uploaded_file.get_uploaded_file())
        return init
```

**Comment by mbraak** [comment]
I can see the need for supporting existing files. I'll see if I can think of a good api.

**Comment by BoPeng** [comment]
For an API, I can imagine an additional `status` field to [`UploadedFileWithId`](https://github.com/mbraak/django-file-form/blob/b733e517c769247dcd57712015daa19341c12a86/django_file_form/models.py#L89) that works like

1. Existing files are presented as `UploadedFileWithId` with `status='existing'` and an empty `UploadedFile`.
2. Such a file will change to status `removed` when deleted, or an real entry if it is replaced with a real uploaded file.
3. Users will need to check `f.status` to remove existing entry with status `removed`, keep existing entry with status `existing`, and add an entry with status `new`.

An option to this approach would be allow users to supply real files to be downloaded or removed, which at least for my application is a bad idea because the files are in S3 and not available locally, and are shared by multiple instances and should not be removed by one instance.
