### ISSUE TITLE
Uppy, tus-js-client, and django-tus?

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#272]
`django-file-form` is based on `tus-js-client`. I was checking if there is a solution for users to perform server-to-server upload and came across [Uppy](https://uppy.io/docs/companion/). It seems that uppy and tus.io were developed by the same team, and uppy provides server to server uploads from locations such as dropbox and google drive, on top of file upload using tus-js-client. I also came across [django-tus](https://github.com/alican/django-tus) which claims to be a "tus server".

I have the following questions 

1. Is it possible to use `uppy` instead of `tus-js-client` to allow server to server upload?
2. What is a `tus` server? Does my server needs to be a tus server (using perhaps `django-tus`) to allow resumable upload from users? Or, has `django-file-form` already made my application a tus server?

**Comment by mbraak** [comment]
`uppy and `tus-js-client` have different javascript apis. This means that `django-file-form` can't use `uppy`.

`django-file-form` includes the `tus` view, which implements the `tus` protocol. So you don't need a separate `tus` server.

The `tus` view is [this file](https://github.com/mbraak/django-file-form/blob/master/django_file_form/views/tus.py).

`django-file-form` could of course add support for dropbox and other sources. But I think that is out of scope of the project at this moment.

**Comment by BoPeng** [comment]
Great. Good to know that no separate `tus` server is needed. Please clarify it in the doc, even adding `django-file-form` to [this list](https://tus.io/implementations.html).

I agree that adding server-to-server upload is out of the scope of this project. If I really need this feature later on, I will fork `django-file-form` and perhaps propose a PR.
