### ISSUE TITLE
Re-upload existing uploaded file lead to two identical files.

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#274]
Is this by design or a bug that should be fixed? When I upload a file twice to a multi-file widget, the file is displayed twice. I expected that the old file is being replaced.

![image](https://user-images.githubusercontent.com/9889312/75617653-ae0a8a80-5b27-11ea-866e-939d4974adb7.png)

**Comment by mbraak** [comment]
It is not really by design, but I'm not sure if it's really an error or unexpected behaviour.

**Comment by BoPeng** [comment]
So we are hitting a blindspot that could be clarified or strengthened. From a users' point of view, I see a lot of scenarios where only one version of the files is needed (e.g. accidental re-uploaded, replacing an old version) and cannot think of one that needs two identical files. Can we change the current behavior?

**Comment by mbraak** [comment]
I'm still not convinced this is a problem for most users. In cases like this a possible solution is to add a hook; something like `onFileUpload`. Then developers can write custom code.

**Comment by BoPeng** [comment]
I looked around. There are different scenarios on this and I think people generally expect:

1. If filenames are the same but file contents are different, or if filenames are different but file contents are the same, both files are kept. 
2. If filenames and contents are both the same, only one file is kept.

To achieve these `djangle-file-form` would need to calculate md5 of uploaded files and check if existing files with the same filename and signature exists, and remove duplicates from the frontend if needed. The problem becomes more complicated with `PlaceholderUploadedFiles` because a "perfect" solution would need users to provide `md5` for placeholder files.

I will work on a PR if this really becomes a problem, but I doubt anyone would complain since the backend of my application already works this way.
