### ISSUE TITLE
Show size of uploaded files.

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#275]
I think it is useful to display the size of uploaded files in the file list so that users can

1. know how big their uploaded files are 
2. identify potential problems e.g. when file is truncated locally or when local and uploaded files have different sizes. 
3. identify which file is new when re-uploading existing uploaded file (#274 )

**Comment by mbraak** [comment]
good idea. i'll put it on the todo list

**Comment by mbraak** [comment]
pr is merged
