### ISSUE TITLE
UploadedFile never "save()" to storage?

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#277]
I specified

```
FILE_FORM_FILE_STORAGE = 'django_hashedfilenamestorage.storage.HashedFilenameFileSystemStorage`
```
with the storage class from https://github.com/ecometrica/django-hashedfilenamestorage/ . The idea is that upon `save()`, the SHA1 hash of `uploaded_file` will be computed and `uploaded_file.file.name` will be changed to the hashed name. The uploaded files could potentially be saved to S3 and duplicated files will not be saved (since their hashes are the same).

It puzzled me for a while that the `uploaded_file` returned from `self.cleaned_data` does not have SHA1 `file.name`. I then searched the source code of `django-file-form` and see that `UploadedFile` was created

https://github.com/mbraak/django-file-form/blob/b733e517c769247dcd57712015daa19341c12a86/django_file_form/views/tus.py#L29

but `save()` is not called anywhere.

Is it true that `UploadedFile` is never saved so `FILE_FORM_FILE_STORAGE` is not used?

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I want to remove the `FILE_FORM_FILE_STORAGE` option because it doesn't work properly. Perhaps it can be added properly in a new version.

**Comment by BoPeng** [comment]
I tried uploading directly to S3 to allow celery workers to process but ended up processing locally before sending to S3, which is faster anyway. 

I agree it is best to remove this option for now. It could be restored with features such as server to server upload so that files are directly available from server.
