### ISSUE TITLE
FILE_FORM_UPLOAD_DIR has to be relative

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#289]
> Issue #266: allow relative FILE_FORM_UPLOAD_DIR setting (thanks to Bo Peng)

But in reality `File_FORM_UPLOAD_DIR` has to be relative because the following line of code ( FileField's 'upload_to' argument must be a relative path, not an absolute path.)

https://github.com/mbraak/django-file-form/blob/7fdc51c44a5bdf4cca37f5937156aaf272a012b7/django_file_form/models.py#L45

This is how `FILE_FORM_UPLOAD_DIR` should behave but you mentioned that you would like to keep backward compatibility, which allowed absolute path.

**Comment by mbraak** [comment]
I will look into it.
