### ISSUE TITLE
Upload callbacks

### ISSUE THREAD

**Issue by editkid** [mbraak/django-file-form#290]
Hello. We used to use `v0.5` with Fine Uploader's [callbacks](https://docs.fineuploader.com/branch/master/api/events.html), like this:

```js
initUploadFields(formElement, {
    callbacks: {
        onComplete: this.handleOnComplete,
        onSubmitDelete: this.handleOnSubmitDelete,
        onValidate: this.handleOnValidate
    }
});
```

Are there any plans to reinstate some callbacks? Or even better can you recommend way to implement callbacks on top of `v2.0`?

I've noticed that the [tus-js-client](https://github.com/tus/tus-js-client) dependency has some callbacks, but they don't seem to be exposed by the `django-file-form` JS API.

Happy to help with implementation. Thank you.

**Comment by mbraak** [comment]
I'll have a look at it.

**Comment by mbraak** [comment]
I added callbacks to this pull request: https://github.com/mbraak/django-file-form/pull/291

It's still  a work in progress, though.

**Comment by mbraak** [comment]
Pr #291 is finished and will be merged shortly. Example of callbacks:

```js
initUploadFields(
  document.getElementById("example-form"),
  {
    callbacks: {
      onDelete: upload => {
        console.log('delete', upload);
      },
      onError: (error, upload) => {
        console.log('error', upload);
      },
      onProgress: (bytesUploaded, bytesTotal, upload) => {
        console.log('progress', bytesUploaded, bytesTotal, upload);
      },
      onSuccess: upload => {
        console.log('success', upload);
      },
    }
  }
);
```

**Comment by editkid** [comment]
This is lovely—thank you for adding these!

**Comment by mbraak** [comment]
pr is merged

**Comment by mbraak** [comment]
closing this issue
