### ISSUE TITLE
Uploading directories

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#292]
`django-file-form` currently reports `Upload failed` when a directory is dropped. Given that there are browser and API support for uploading entire directories, is this a bug or some feature that has not been implemented?

**Comment by mbraak** [comment]
I'll have a look at it.

**Comment by mbraak** [comment]
I added a pr: https://github.com/mbraak/django-file-form/pull/298
This is still experimental though.

**Comment by mbraak** [comment]
This is merged in master.
