### ISSUE TITLE
Forgotten makemigrations so a migration is added once you have django-file-form installed

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#300]
Hi there, is it possible to release a new version with the new migration added? Anyone that now runs makemigrations on their own machine/server will get a django-file-form migration added as well:
```
Migrations for 'django_file_form':
  /lib/python3.6/site-packages/django_file_form/migrations/0005_auto_20200407_1223.py
    - Alter field uploaded_file on uploadedfile
```

**Comment by mbraak** [comment]
I added a pr (#301). It will be merged shortly.

**Comment by mbraak** [comment]
Pr is merge. Closing the issue.

**Comment by Lionqueen94** [comment]
Hi @mbraak the added migration is not sufficient it seems, because I get the message there are still new changes not reflected: `- Alter field uploaded_file on uploadedfile` I have the most recent version installed and performed `python manage.py migrate`

**Comment by mbraak** [comment]
I can reproduce this error. Changing the `FILE_FORM_UPLOAD_DIR` will change the migration. I will see if I can fix this.
