### ISSUE TITLE
Client side validation after dropping files and before form submission

### ISSUE THREAD

**Issue by sks444** [mbraak/django-file-form#317]
Is there a way to validate the dropped files in the drop area at client side before user is submitting the form?

I have validation in backend which ultimately throws error saying these file types are not allowed. Would be good to let user know that when they drop the files and before they submit the form.

I have set the accept attribute in the input tag so user can not select invalid file types when they are going through choose file option. But they can still drop any files' types, is there a way to avoid that too?

**Comment by mbraak** [comment]
At this moment that is not possible. I'll write this down as a possible feature / fix.

**Comment by mbraak** [comment]
There is a pr for this that is almost finished: #329

**Comment by mbraak** [comment]
Fixed in `master`
