### ISSUE TITLE
Bug in UploadMultipleWidget

### ISSUE THREAD

**Issue by sks444** [mbraak/django-file-form#318]
In case where there are two file fields on a form.

`get_place_holder_files_from` method returns placeholder files for the first field it finds.
https://github.com/mbraak/django-file-form/blob/a2e723a29f7fbf33717af63746cb92d42515739d/django_file_form/widgets.py#L63

Possible approach to solve this would be to send the `name` parameter to `get_place_holder_files_from` and do `field.replace('placeholder-', '') in data.keys()` instead of looking for the key.
https://github.com/mbraak/django-file-form/blob/a2e723a29f7fbf33717af63746cb92d42515739d/django_file_form/widgets.py#L55

Let me know if this seems like a valid issue, I can send in a pr.

**Comment by mbraak** [comment]
Yes, this is a valid issue. Please send a pr if you have one.

**Comment by mbraak** [comment]
Fixed in pr #320
