### ISSUE TITLE
Javascript api

### ISSUE THREAD

**Issue by mbraak** [mbraak/django-file-form#321]
A javascript api that allows to:

* access the upload fields in a form
* query the uploads: which files are uploaded
* remove an upload
* set custom attributes
* handle events
* more?

It could look something like this:

```
const fileForm = initUploadFields(document.getElementById('example-form'));

fileForm.getFields();
fileForm.getField('testImageUpload').getUploads();
```

**Comment by BoPeng** [comment]
Thanks. I will be the first to port our patch to test your API.

**Comment by BoPeng** [comment]
@mbraak @jma7 Are there events for the addition and removal of `dff-file` div that we can `addEventListener` to? I gave a little bit more thought on this ticket before I re-implement our `primary` button feature and thought that, as long as some customized functions can be called after the addition and removal of the file `div`, it should be relatively easy for us to add, remove and respond to our own widgets. 

Then in the backend we could add a hidden input in the form and a model field called `self.meta = {}` that bridges backend and frontend widget. We have done this multiple times.

I can work on a PR if you guys can give me some guidance on the "plugin/event" mechanism in the frontend.

**Comment by mbraak** [comment]
There are no events for addition or removal at the moment. I can make a pr that adds those events.

My idea for the api:

```js
const fileForm = initUploadFields(...);

fileForm.on('addUpload', ({ element, upload }) = {
  // custom code
  // element is the dff-file div
  // event is fired when the upload is started ?
  // also when the form is reloaded with an existing upload ?
};

fileForm.on('removeUpload', ({ element, upload }) => {
 // event is fired before the upload is removed ?
});
```

The original idea for a javascript api is not practical at the moment. It's a good idea to start small with some events.

**Comment by mbraak** [comment]
I added a pr with a basic implementation: #341.

The original api with a `fileForm` did not work for existing files. The new api is:

```js
import EventEmitter from 'eventemitter3';

const eventEmitter = new EventEmitter();

initUploadFields(
    document.getElementById("example-form"),
    {
      eventEmitter,
    }
);

eventEmitter.on('addUpload', ({ element, fieldName, upload }) => {
  // upload could be an `Upload` or `S3Uploader` or a simple object for an existing upload or a placeholder upload.
  console.log('addUpload', element, fieldName, upload);
});

eventEmitter.on('removeUpload', ({ element, fieldName, upload }) => {
  console.log('removeUpload', element, fieldName, upload);
});
```

* This depends on the `eventemitter3` package: https://www.npmjs.com/package/eventemitter3
* The question is if this api is enough to implement to primary checkbox.

**Comment by BoPeng** [comment]
> The question is if this api is enough to implement to primary checkbox.

Not enough without the Python part, but I will add it.

**Comment by mbraak** [comment]
Closing this issue. This is being handled in different prs.
