### ISSUE TITLE
Get placeholder file for UploadWidget

### ISSUE THREAD

**Issue by sks444** [mbraak/django-file-form#324]
For `UploadMultipleWidget` we get the [new uploaded files + placeholder files](https://github.com/mbraak/django-file-form/blob/d1ed580a9878d994031b2e688e0a9c07128c407a/django_file_form/widgets.py#L63) while processing edit forms. So we can decide which ones to keep in our db and which ones to delete.

But for `UploadWidget` we don't get the placeholder file: so while processing edit forms: assuming that I have a file uploaded to single file upload widget:

- If I do not upload a new file while editing and then do submit, I won't get anything:
  - this means I should not touch my db files, which is okay.
- But If I deleted the already uploaded file while editing and then did submit, I still won't get anything:
  - now there is no way to know if the file was deleted.

---

This could be solved by doing:
- If user didn't do anything:
   - return the placeholder file, don't touch db files

- so If user deleted the placeholder file, I won't get anything and I can update my db accordingly.

- If a new file is uploaded:
   - return the new file, update the db files

Possible code snippet that can be added to `UploadWidget` class:

```python
class UploadWidget(UploadWidgetMixin, ClearableFileInput):
    def get_place_holder_file_from(self, data, name):
        for field, value in data.items():
            # if we have two fields A, placeholder-A, or prefix-A, prefix-placeholder-A
            # then placeholder-A is a placeholder hidden field
            if 'placeholder-' in field and field.replace('placeholder-', '') == name:
                placeholder_file = [
                    PlaceholderUploadedFile(name=x['name'], size=x['size'], file_id=x['id'])
                    for x in json.loads(value)
                ]
                return placeholder_file[0] if placeholder_file else None
        return

    def value_from_datadict(self, data, files, name):
        upload = super().value_from_datadict(data, files, name)
        if not upload:
            return self.get_place_holder_file_from(data, name)
        return upload
```
@mbraak let me know if this seems like a valid issue, I can send in a pr to implement this.

**Comment by mbraak** [comment]
Yes, this seems like a valid issue. I would welcome a pr.
