### ISSUE TITLE
Error in deleting files.

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#331]
How to reproduce:

1. On master
2. Upload a bunch of small files
3. Delete files 2, 3, 4, 5, etc, and at some point the file cannot be deleted.

Reason:

https://github.com/mbraak/django-file-form/blob/ed902f72cc915a38c5f4936342de7ccb97028d67/frontend/src/upload_file.ts#L267

Seems to be using `data-index` of the `Delete` action, but `this.uploads` becomes smaller after deletion.

https://github.com/mbraak/django-file-form/blob/ed902f72cc915a38c5f4936342de7ccb97028d67/frontend/src/upload_file.ts#L281

So at some point

https://github.com/mbraak/django-file-form/blob/ed902f72cc915a38c5f4936342de7ccb97028d67/frontend/src/upload_file.ts#L278

`uploadIndex` will get out of index.

It seems that `data-index` should be updated after the removal of each file. However, if users click very fast, the incorrect `data-index` link could be triggered before the `data-index` is updated. Perhaps we should make `data-index` a UUID instead of an index.

**Comment by mbraak** [comment]
I can reproduce this error if I click multiple times on the same delete link. I will look into it.

**Comment by mbraak** [comment]
Note that `delete this.uploads[uploadIndex]` sets `this.uploads[uploadIndex]` to undefined. So it doesn't change the indexes.

**Comment by BoPeng** [comment]
> Note that `delete this.uploads[uploadIndex]` sets `this.uploads[uploadIndex]` to undefined. So it doesn't change the indexes.

Indeed, this is different from Python where `del a[1]` will actually reduce the size of `a`. I will leave it to you to figure out the problem then.

**Comment by mbraak** [comment]
Fix is pr #332. Will be merged shortly.
