### ISSUE TITLE
Admin integration

### ISSUE THREAD

**Issue by DataGreed** [mbraak/django-file-form#339]
Is there any way to use this library with django admin to upload files asynchronously? In my case I have a form with a lot of inlines. Each inline has a file field an I would like to be able to upload a lot of files at once while continuing working with the page.

**Comment by mbraak** [comment]
I have never done that, but it should be possible.

* You need to be able to define an admin form with `FileFormMixin`.
* You have to run some custom javascript to call `initUploadFields` on each form.

**Comment by DataGreed** [comment]
@mbraak thanks! Going to check it out

**Comment by mbraak** [comment]
This is now supported in version 3.1.5. See http://mbraak.github.io/django-file-form/admin/
