### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by sebhaase** [mbraak/django-file-form#350]
I think it is "just confusing" that in section `Details - 3 Adding placeholder files` the example file name `'manage.py'` is used (at two places). That filename has obviously a special meaning in the django context.  I would rather suggest a filename like `myUploadedAndMovedImagefile.jpg` ...
Thanks, Seb.

**Comment by mbraak** [comment]
I will change this in the readme.

**Comment by BoPeng** [comment]
lol, I happened to be testing the code in the directory with `manage.py`. :-)

**Comment by mbraak** [comment]
fixed
