### ISSUE TITLE
Anything similar to s3_upload_dir for tus upload?

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#352]
I am using `s3_upload_dir = self.request.user.username` to separate uploads from multiple users and found it convenient.Perhaps I have missed something obvious but I am wondering if `django-file-form` has a similar mechanism for adding form specific subdirectory for `tus` upload. If not, can we add something to balance the feature sets for `tus` and `s3` uploads?

**Comment by mbraak** [comment]
It is of course possible to save the end result to a specific directory (in the form.save). But this feature does not exist for the temporary files (in `media/temp_uploads`). We can add this feature, but I would like to know the use case.

**Comment by BoPeng** [comment]
Say for example an application has a few upload forms, one for teacher to upload their tests and one for students to upload their completed ones. It would be easier to see what has uploaded who from S3 or admin interface.Here the form-specific directory could be by user name or by role.

Also for example an application have a large amount of uploads that could be ignored and orphaned by the application. If the form upload by date then it would be easy to delete unprocessed uploads from backend.

In general it is difficult for me to justify a large site having all uploads from all users dumped into the same directory.

**Comment by mbraak** [comment]
Yes, it seems more useful on S3. This has no priority at the moment.
