### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mbraak** [mbraak/django-file-form#362]
There are a lot of new features in master, like s3. Let's release a new version.

**Comment by BoPeng** [comment]
With #359 and #361 open? I understand the event API is considered to be experimental though.

**Comment by mbraak** [comment]
Yes, the event api is experimental. And I don't know how long the upload refactoring is going to take, so I don't want to wait on that.

**Comment by mbraak** [comment]
Version 3.1.0 is released
