### ISSUE TITLE
Customize frontend UI

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#421]
Right now the UI consists of a button and a drop area. What is the best way to customize this, say, if I want to have something like the following? Perhaps a event handler could be defined and allows users to draw its own UI?

![image](https://user-images.githubusercontent.com/9889312/104530977-c914aa80-55d2-11eb-9aad-b5488086d00f.png)

**Comment by mbraak** [comment]
One solution that I can think of:

If no files are uploaded, the class `dff-empty` is added to the `.dff-files` div. This allows you to customize the drop area with css.

I can add an option to change the 'Drop your files here' message. The only thing missing is the 'click to upload' link. I don't know how that would work.

**Comment by BoPeng** [comment]
`click to upload` would replace the "browse" button. This layout is a bit cleaner than the default one because it has a single widget, although the "click to upload" link would be gone (?) once files are added (or the file list should be put elsewhere).

I am not saying that I like this layout, just curious what is the best way to customize the frontend widget.

**Comment by BoPeng** [comment]
Actually I do not quite understand why the widget should be dynamically created in JS. Why cannot it be put into [upload_widget.html](https://github.com/mbraak/django-file-form/blob/master/django_file_form/templates/django_file_form/upload_widget.html) ?

**Comment by mbraak** [comment]
The widget should also work without javascript. Without javascript there is only an upload input.

**Comment by mbraak** [comment]
I guess it's possible to add a custom handler for the ui. But it's difficult to define what it should do. It's a lot easier to add a very specific handler, like: draw the message for the empty dropbox.

**Comment by BoPeng** [comment]
To cover up the default upload button, I had to do something like the following in `upload_widget.html`

```
<div class="dff-uploader">
    <div class="dff-container" {% if uploaded_files %} data-files='{{ uploaded_files }}' {% endif %}
        data-translations="{{ translations }}">

        <div class="custom_upload">
            <label for="{{ input | get_id }}">
                {{ input }}
                <span class="btn btn--round btn--sm">Choose File</span>
            </label>
        </div>
    </div>
</div>
```

The problem is that `input` is not passed in as a `widget`, but as a rendered string

https://github.com/mbraak/django-file-form/blob/fce6903e342ac9749e8213162b0ac6e91f063f9f/django_file_form/widgets.py#L99-L108

so I had to define a customized template tag to extract the id. Perhaps `input` should be passed directly?

Anyway, with more css and fake translation of `delete` and `cancel` button, the result is

![image](https://user-images.githubusercontent.com/9889312/107970572-e55f8a80-6f76-11eb-8562-86cb3155ac8c.png)


![image](https://user-images.githubusercontent.com/9889312/107970641-ff00d200-6f76-11eb-8708-0292dd8a56cf.png)

**Comment by mbraak** [comment]
I will have a look

**Comment by mbraak** [comment]
I think the rendered input has to be included, because I don't see how it can be rendered in `upload_widget.html`.

An alternative solution could be to add `attrs` to the `upload_widget.html`. Then the id can be accessed in the template:

```
{{ attrs.id }}
```

Please let me know if this is a solution in your case.

**Comment by BoPeng** [comment]
A proper way seems to extend `get_context` which would allow me to use `widget.id` in the template. I just proposed an PR for this change.
