### ISSUE TITLE
How to translate Delete to an icon?

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#428]
The `delete` element is

```
<a href="#" data-index='whatever">_("Delete")</a>
```
and I would like to change it to 

```
<a href="#" data-index='whatever"><span class="lnr upload_cross lnr-cross"></span> </a>
```

Hacking the translation like

```
from django_file_form import widgets

from .models import Attachment, AttachmentManager, SharingPermissionManager, Workflow
widgets.TRANSLATIONS['Cancel'] = '<span class="lnr upload_cross lnr-cross"></span>'
widgets.TRANSLATIONS['Delete'] = '<span class="lnr upload_cross lnr-cross"></span>'

```
in my `forms.py` does not appear to work.

**Comment by BoPeng** [comment]
It does not work because when the button is clicked, the frontend is

https://github.com/mbraak/django-file-form/blob/643d0a6a418577e59a70ed21ca6afc68dec5d4b7/frontend/src/file_field.ts#L284-L285

checks if the button has the classes, but only the parent class has them...

**Comment by BoPeng** [comment]
Whereas I still do not understand why the event is not bubbled up,

```
widgets.TRANSLATIONS['Cancel'] = '<span class="lnr upload_cross lnr-cross" style="pointer-events: none"></span>'
widgets.TRANSLATIONS['Delete'] = '<span class="lnr upload_cross lnr-cross" style="pointer-events: none"></span>'
```

appears to do the trick.

@mbraak You can close the ticket if think the event is how it was suppose to be handled.

**Comment by mbraak** [comment]
Ok, closing the ticket.
