### ISSUE TITLE
Path elements in S3Boto3StorageFile.name causes trouble with FileField for django 2.2.20+

### ISSUE THREAD

**Issue by BoPeng** [mbraak/django-file-form#461]
`S3Boto3StorageFile` parallels `UploadedTusFile` as one type of `UploadedFile` objects returned from `django-file-form`. They are most likely saved to database as `FileField` with different storage backends. In particular, at least in my case, `FileField.name` has been set as `S3Boto3Storage.name` as the object name in S3 with a `S3Boto3Storage` storage. 

Django 2.2.20 (2.2.21, 3.1.?+) introduced [this patch](https://github.com/django/django/commit/04ac1624bdc2fa737188401757cf95ced122d26d) that disallows `FileField.name` to have any path element. This change has caused a lot of broken code (e.g. [pulp](https://pulp.plan.io/issues/8691)), including mine because my the object name saved in `FileField.name` contains `/` (`${FILE_FORM_UPLOAD_DIR}/${s3_upload_dir}/FILENAME`).

I am not sure if I was supposed to save S3 object name as `FileField.name` so I post a question on [django-storage](https://github.com/jschneier/django-storages/issues/1011). I am posting this issue here in case others have the same problem as me.

**Comment by BoPeng** [comment]
Just to clarify why this problem concerns `django-file-form`. Suppose we use `django-file-form` and the data is already on S3, with object name   `${FILE_FORM_UPLOAD_DIR}/${s3_upload_dir}/FILENAME`, how exactly should the webserver store this information to the database? Right now the only solution appears to be setting `name` as `FILENAME` and `upload_to`  to as `${FILE_FORM_UPLOAD_DIR}/${s3_upload_dir}`, but that is vastly inconvenient if, say, `s3_upload_dir` is username.

**Comment by BoPeng** [comment]
I have fixed the problem by defining a `upload_to` function that yields the correct object name on S3 for different situations. It is more troublesome than before but this is the best I can do.

**Comment by balazs-endresz** [comment]
I haven't followed this closely but this might be related: https://code.djangoproject.com/ticket/32718 There should be a new patch soon.

**Comment by mbraak** [comment]
This is fixed in Django 3.2.3 (also in 2.2.23)

https://docs.djangoproject.com/en/3.2/releases/3.2.3/
