### ISSUE TITLE
Option FILE_FORM_MAX_FILE_SIZE doesn't work

### ISSUE THREAD

**Issue by mbraak** [mbraak/django-file-form#464]
The `FILE_FORM_MAX_FILE_SIZE` doesn't seem to work. 

The option sets the `Tus-Max-Size` value in the header, but the value is not recognized by the tus-js-client (https://github.com/tus/tus-js-client). Note that `Tus-Max-Size` is in the tus protocol: https://tus.io/protocols/resumable-upload.html#tus-max-size

Also see #463

**Comment by sebhaase** [comment]
You could have renamed my ticket to this :-)     #463 
In any case the option could be remove, it it doesn't do anything....

**Comment by sebhaase** [comment]
Just for future reference:

https://tus.io/protocols/resumable-upload.html#tus-max-size:
"The Server SHOULD set this header if there is a known hard limit."

So maybe in the future we could consider adding this part of the TUS protocol...

And the pull request closing this issue is #465
