### ISSUE TITLE
MultipleUploadedFileField in modelform return None input_files with S3 upload

### ISSUE THREAD

**Issue by typh289** [mbraak/django-file-form#468]
With MultipleUploadedFileField i get always None in cleaned_data with a modelform, working fine instead with a single UploadedFileField, and also multiple on form instead of a modelform or without S3 so i got quite stuck, maybe someone can point me in the right direction of where the issue could be or reproduce this?
on django 3.2.3 and with django-file-form 3.2.1 (was 3.2.0 at first but tried with both 3.2.1 and master)

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I added an example to [this branch](https://github.com/mbraak/django-file-form/pull/469/files). The example seems to work fine:

![Screenshot 2021-06-26 at 12 08 17](https://user-images.githubusercontent.com/235558/123509775-d05adc80-d677-11eb-87bc-c72df4b5d695.png)

**Comment by typh289** [comment]
Thank you for checking it out, guess it's something about my project then i'll have a better look and eventually update with more details, i get input_file-uploads correct and temp files get written on S3 but input_file None, i forgot to mention that i'm also using a formset actually there so maybe it complicates things further, it confused me a little that with UploadedFileField i had no issues

**Comment by mbraak** [comment]
I think I can reproduce the error. I'll have a look.

**Comment by mbraak** [comment]
I added a fix to the [add-model-form-s3-example](https://github.com/mbraak/django-file-form/pull/469/files) branch. It seems to fix the issue with the modelformset with s3.

**Comment by typh289** [comment]
Yes can confirm, looks fixed with that!

**Comment by mbraak** [comment]
Fixed in version 3.2.2
