### ISSUE TITLE
Error: Cannot find template script at ID 'qq-template'!

### ISSUE THREAD

**Issue by Karmak23** [mbraak/django-file-form#47]
Hi,

I use the file-form with Django 1.6.10.

After having upgraded to @master recent version, and done a `migrate`, the uploader is broken and the browser console says :

```
Error: Cannot find template script at ID 'qq-template'!
```

I tried hunt a little, but didn't find anything relevant at first sight. What could be related to this problem ?

Thanks & regards,
Olivier

**Comment by mbraak** [comment]
Hello Olivier,

In the new version you have to add the following to your template:

```
{% include 'django_file_form/upload_template.html' %}
```

Also see [this example template](https://github.com/mbraak/django-file-form/blob/master/testproject/django_file_form_example/templates/example_form.html).

Greetings,
Marco

**Comment by Karmak23** [comment]
Sorry, I totally missed that.

With the template included, the form works correctly when clicking the "upload a file" button.

But If I want to drag'n'drop a file from my desktop (Arch Linux / Gnome Shell / Nautilus) to the browser (Firefox), the upload form drop area doesn't show, and if I drop the file "as usual", firefox asks me if I want to download the file, instead of launching the upload.

I double checked the example project and I do not seem to miss anything. In the failing page I have 3 upload forms. Hint: it worked perfectly before ;-) What did I miss again ?

Thanks for your support,

**Comment by mbraak** [comment]
I think that drag-and-drop might be broken in the latest master. I will look into it.

**Comment by mbraak** [comment]
It is now fixed in the master branch.
Greetings

**Comment by Karmak23** [comment]
**THANKS** :-)

**Comment by Karmak23** [comment]
I confirm it's fixed. Thanks again !
