### ISSUE TITLE
How to append input files instead of replacing when the user picks the files again?

### ISSUE THREAD

**Issue by BismeetSingh** [mbraak/django-file-form#473]
I  would like to allow the user to make file selection multiple times. I will show the selected file names in  a table below and would like to add the newly selected file to the table.

**Comment by mbraak** [comment]
There is a EditModelFormMultipleView view in the example project that does this. https://github.com/mbraak/django-file-form/blob/dbe8090c3f7dd3f4bb626e201335bfe06d2a2f85/testproject/django_file_form_example/views.py#L232

To see this working in the testproject. The url for creating is: http://localhost:8000/model_form_multiple For editing: http://localhost:8000/model_form_multiple/[id]

This example works with a ModelForm, but it should also be possible with a normal form. The trick is to override `get_initial`.

**Comment by BismeetSingh** [comment]
Also, is there a way to allow the user to remove the files?
Kinda like this:
![image](https://user-images.githubusercontent.com/13601266/124710427-64e7f900-df1a-11eb-9039-a465bbcbc13b.png)

**Comment by mbraak** [comment]
Yes, the form has a 'delete' link.

This is from the example project:

<img width="417" alt="Screenshot 2021-07-07 at 18 05 10" src="https://user-images.githubusercontent.com/235558/124793196-0b012680-df4e-11eb-9386-0d630090c818.png">

**Comment by BismeetSingh** [comment]
Couldnt figure out how to add multiple files. Solved using dropzone.js . Thanks anyway.
