### ISSUE TITLE
Getting 's3_upload' is not a valid view function or pattern name. despite setting up URLs to include django_file_form

### ISSUE THREAD

**Issue by giblet17** [mbraak/django-file-form#484]
I'm confident I'm doing something silly but I can't get to the bottom of it. I've added
    path('upload/', include('django_file_form.urls')),

to my urlpatterns. But when I attempt to load the form which would use s3 to store uploaded files I get:
    Reverse for 's3_upload' not found. 's3_upload' is not a valid view function or pattern name.

I can see the url in s3_multipart.urls. It looks like my include('django_file_form.urls') simply isn't working but I've no idea why.

p.s. Installed django-file-form today (and love it). Using Django 3.2.6

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I think the s3 urls are only loaded if the `boto3` package is installed. It also needs the `django-storages` package.

This is missing from the docs, I'll add it.

**Comment by giblet17** [comment]
Ah yes, django-storages was missing for me. Installed now, and no longer encountering this issue.

Thanks very much for your help and for this very helpful package.

Warm regards,
Will
