### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by mi01** [mbraak/django-file-form#574]
Hello,

thank you for contributing this nice extension. Using it in my local test environment was no problem. After deploying it to my production server I stumbled over some issues, so I want to share my experience here ...

- I run my production environment with gunicorn and nginx. The file upload worked sometimes, but sometimes I got an error "Upload failed". This was really strange, so I started investigating. It turned out that I got sometimes a 410 response when uploaded the image with PATCH, triggered by this line: https://github.com/mbraak/django-file-form/blob/4b116be132b105791b7991784ea9099fca3e0364/django_file_form/tus/views.py#L123
After debugging the problem, it turned out that the filename was None when the upload failed and the filename is retrieved from the Django cache. I was using the default local-memory caching then, which is per-process. Since gunicorn was running with more than one worker process, there were cache misses sometimes. At least I think so, since the problem disappeared after configuring Memcached.

- After solving the first problem I still got "Upload failed" sometimes. But here it was obvious, since the server response was "413 -  Request Entity Too Large". Changing `client_max_body_size` in my nginx config solved this problem. But it would be great improvement to forward this response to the user with a dedicated error message like "File size too large!".

Maybe this obstacles should be mentioned at least in the documention?

My setup:
_gunicorn 20.1.0
django-file-form 3.4.2
django 4.1.5_

**Comment by mbraak** [comment]
I'll look into it.

**Comment by mbraak** [comment]
I added a 'production' setting to the documentation: http://mbraak.github.io/django-file-form/details/#production

**Comment by mi01** [comment]
Thanks, I think this solved the deployment issues I had.
