### ISSUE TITLE
rename file_form.js to file_form.min.js?

### ISSUE THREAD

**Issue by bioworkflows** [mbraak/django-file-form#669]
This is a very minor issue but why [file_form.js](https://github.com/mbraak/django-file-form/blob/master/django_file_form/static/file_form/file_form.js) is not named `file_form.min.js` if it is indeed minified? I was asked why I include a non-minified js file in our production server and I had to explain that this file is indeed minified.

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I changed the filename to `file_form.min.js`. The `file_form.js` file is now the non-minified version. I plan to release a new of version of django-file-form this week.

**Comment by BoPeng** [comment]
Thanks!

**Comment by mbraak** [comment]
Version 3.5.2 is released. It includes this fix.
