### ISSUE TITLE
check_permission() - anonymous?  when to fail?

### ISSUE THREAD

**Issue by sebhaase** [mbraak/django-file-form#676]
I'm trying to extend my permissions scenario - who should be allowed to upload...
1. I noticed that non-logged-in users get only  "Upload failed" message without any info why. - I traced that down to utils.py `check_permissions()` which in turn gets called by https://github.com/mbraak/django-file-form/blob/5cb31a5b61b0576f3a6f9e4739c3eb4ed0be6ff9/django_file_form/tus/views.py#L22

2. then I logged in as a user who should not be allowed to upload -- there I found that the upload still happend into the temp folder - since I only check permissions in my `form clean(self)` function 

What is the best way of providing meaningful error message and doing the checks as early as possible?   is this docuemented (I did not see it...)

Thx, Sebastian

**Comment by mbraak** [comment]
I'll check if the upload to the temp folder can be prevented.

About the permissions: one solution is to disable uploads. Would that be a solution? I think it's not possible at this moment to disable uploads. I'll check that.

**Comment by mbraak** [comment]
A possible solution is to make the field disabled when the user doesn't have the permission to upload. Pr #680 adds support for disabled fields.

Another solution is to hide the field.

**Comment by sebhaase** [comment]
I am really only concerned with a server side check.

**Comment by mbraak** [comment]
I'll check if it's possible to display an error message.

It's a good idea to check as early as possible if a user has permission to upload; the easiest solution is to make the `check_permission` function configurable. 

In the settings file:

```python
def custom_check_permission(request):
  if not request.user.is_authenticated:
    raise PermissionDenied()

FILE_FORM_CHECK_PERMISSIONS_FUNCTION = custom_check_permission
```

Would that work in your situation?

**Comment by sebhaase** [comment]
Something like that I already tried (via hacky function overloading).
And the error message I wrapped inside a custom PermissionDenied derived
class.
My solution is not perfect yet, though…
Sebastian.


Marco Braak ***@***.***> schrieb am Mo. 12. Juni 2023 um
17:36:

**Comment by sebhaase** [comment]
I have another issue ... to *really* determine if the upload should be allowed, I would need to get values from other fields of the form... I don't see how that would be at all possible...
So, guess that part comes down to the question of how to *delete* temp uploads on failed (or never triggered) save...

**Comment by mbraak** [comment]
The form has a `delete_temporary_files` method that removes all temporary files. So that's in the right direction.

I can have a look later if it's possible to remove files for a single field.

**Comment by mbraak** [comment]
I added the method `delete_temporary_files_for_field` in pr #689.

**Comment by mbraak** [comment]
Does pr #689 fix the issue?

**Comment by sebhaase** [comment]
Hi Marco, sorry for the delay...
I'm sorry, but I cannot follow this issue at the moment because I do not
understand enough about what the meaning of the "for fields"-part should
be.  I somehow already have a working hack for my original problem, sorry...
