### ISSUE TITLE
Is it possible to initialize the file upload in React?

### ISSUE THREAD

**Issue by Lionqueen94** [mbraak/django-file-form#714]
Hi there,

Is it possible to initialize the file upload in React? We currently use an old version of Django file form and create our own Upload frontend code with the Upload component from tus-js-client. I see this same component is used in the current frontend code in the latest version of Django file form.
Could the frontend code be made available on npmjs.com for example to be installed (package.json) and used in React?
We are going to update our platform to work with the latest version of Django file form and would love to get rid of duplicate code (that now exists in your frontend folder).

Thanks in advance for your reply.

With kind regards,
Ellen

**Comment by mbraak** [comment]
No, I'm afraid making a npm package of the frontend code is outside the scope of this project.
