### ISSUE TITLE
Support (or example) for Inlines

### ISSUE THREAD

**Issue by dtcooper** [mbraak/django-file-form#740]
I'm trying to get django-file-form to work in Django's admin with inlines (`InlineModelAdmin`'s subclasses `TabularInline` and `StackedInline`).

Here's what I've tried,

```python

# Tried both subclassing the inline with FileFormAdminMixin and without
class MyModelInline(FileFormAdminMixin, admin.TabularInline):
    model = MyModel

class MyOtherModelAdmin(FileFormAdminMixin, admin.ModelAdmin):
    inlines = (MyModelInline,)
```

Any ideas?

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
There is an example in the repository: https://github.com/mbraak/django-file-form/blob/master/testproject/django_file_form_example/admin.py (Example2Admin).

**Comment by mbraak** [comment]
The example doesn't seem to work. I'll have a closer look.

**Comment by mbraak** [comment]
Inline forms are not supported. There are no plans at this moment to support it. But pull requests are still welcome.
