### ISSUE TITLE
Drag and drop available?

### ISSUE THREAD

**Issue by angelika** [mbraak/django-file-form#86]
Is there a way to enable drag and drop? There seems to be support for it in the js, but I can't figure out how to enable it. Or is it a browser support thing?

**Comment by mbraak** [comment]
You don't have to enable it, it should work out-of-the-box. I tested this on Chrome on OSX, and it seems to work.

If you drag a file from the finder to your browser, then you get the message 'drop files here to upload'.

**Comment by angelika** [comment]
Ah, you have to actually start dragging the file to the browser for the message to show! That bit escaped me :) Ok, thanks, it works great!

**Comment by mbraak** [comment]
great, closing the issue
