### ISSUE TITLE
Validate size or file type

### ISSUE THREAD

**Issue by angelika** [mbraak/django-file-form#87]
Is there a way to add limitations, like only allowing images (and not other types of files) to be uploaded and/or only up to a certain size?

**Comment by mbraak** [comment]
You can add options to the **initUploadFields** function. At this moment this feature is not documented.

This example only accepts images and limits the size to 10000 bytes:

```js
initUploadFields(
    $('#example-form'),
    {
        validation: {
            acceptFiles: 'image/*',
            sizeLimit: 10000
        }
    }
);
```

Djang-file-form uses [fineuploader](http://fineuploader.com/) under the hood. The **validation** options in the example are fineuploader options. Please see [fineuploader docs about validation options](http://docs.fineuploader.com/branch/master/api/options.html#validation) for more information.

**Comment by angelika** [comment]
Wonderful, thank you!

**Comment by mbraak** [comment]
great. closing the issue
