### ISSUE TITLE
Formset support?

### ISSUE THREAD

**Issue by patpatpatpatpat** [mbraak/django-file-form#96]
Are you planning to add support for formsets? I think it would be a great feature.

I tried using using Django's `modelformset_factory` with the form and rendering the formset in the template and used your instruction for the single form, but I'm getting this error when uploading a file in one of the forms:

`fileuploader.js:203 [Fine Uploader 5.0.8] Error when attempting to parse xhr response text (Unexpected end of input)`

**Comment by mbraak** [comment]
I'll try to reproduce the error

**Comment by mbraak** [comment]
I get the same error message. The problem is that formsets change a lot of things; the django-file-form code does not support that.

At this moment I don't want to add support for formsets. It would take quite an effort, and it's a feature I don't use myself.

**Comment by patpatpatpatpat** [comment]
Alright, thanks! :+1:
