### ISSUE TITLE
Add drag and drop support for image uploads with Sortable.js

### ISSUE THREAD

**Issue by lucabfelix** [mbraak/django-file-form#965]
It would be very useful to add support for handling drag and drop image uploads. Similar to what the [image-uploader-widget](https://inventare.github.io/django-image-uploader-widget/) lib does. It was the only lib I found for django with this feature, but there are still [bugs](https://github.com/inventare/django-image-uploader-widget/issues) to fix.

**Comment by mbraak** [comment]
Yes, this would be a nice feature. However, I have no plans to add new features to django-file-form at the moment.
